##########################################################
###################  开发环境的profile  ###################
##########################################################

spring:
  datasource:
      url: jdbc:mysql://192.168.70.82:3306/test_silkroad?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
      username: root
      password: Ebh123!@#
      druid:
        initial-size: 5


  freemarker:
    settings:
      template_update_delay: 0 #0秒刷一次

logging:
  level:
    root: info
    com.adyx: info


