##########################################################
###################  开发环境的profile  ###################
##########################################################

spring:
  datasource:
    url: jdbc:mysql://192.168.70.82:3306/vulcan_dev?useUnicode\=true&characterEncoding\=UTF-8&autoReconnect=true
    username: root
    password: Ebh123!@#
    druid:
      initial-size: 5


  freemarker:
    settings:
      template_update_delay: 0 #0秒刷一次

logging:
  level:
    root: info
    com.adyx: info


